POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"",
    "password":"aaaaaa",
    "confirmPassword":"vykt2000",
    "email":""
}

####
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"vyhungles",
    "password":"vykt2000"
}

####
POST http://localhost:5000/api/product/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmE0ZWU3YzA4MDA5M2I5MDY3Zjg1YiIsImVtYWlsIjoidnl1bmdsZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjIzNzcxNDEwLCJleHAiOjE2MjQ5ODEwMTB9.BtFnUOnL19DF2LfUhIsc1t8OGErlMLYdV0kiGqvZZRo
Content-Type: application/json

{
    "name":"Coca Cola Light",
    "image":"https://storage.googleapis.com/teko-gae.appspot.com/media/image/2020/5/10/20200510_7406856a-d49b-478a-ba23-b82bcd5e60b2.jpe",
    "unit":"lon 330ml",
    "quantity": 200,
    "price": 9500,
    "discount": 4.5,
    "detail":"Nước giải khát không đường Coca Cola Light lon 330ml mang hương vị cola độc đáo giúp giải nhanh cơn khát của bạn. Đặc biệt, dòng sản phẩm Coca Cola này không chứa đường nên rất phù hợp với những người ăn kiêng. Nước giải khát không đường Coca Cola light được sản xuất trên dây chuyền công nghệ hiện đại, đảm bảo vệ sinh.",
    "categoryId":"60cda59f8ade223758d7387a",
    "producerId":"60c8c253ee2a4a9a80bb71be",
    "supplierId":"60c8c253ee2a4a9a80bb71be"
}

####
GET http://localhost:5000/api/product/all


####
GET http://localhost:5000/api/product/60bb283126978520449fae32


####
PUT http://localhost:5000/api/product/update/60bb283126978520449fae32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmE0ZWU3YzA4MDA5M2I5MDY3Zjg1YiIsImVtYWlsIjoidnl1bmdsZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjIyODc5ODQ4LCJleHAiOjE2MjQwODk0NDh9.DnkxmqzfNretOr0d6_hvFXI8P0-KX38WzlUDR6tAFuY
Content-Type: application/json




####
DELETE http://localhost:5000/api/product/delete/60bb283126978520449fae32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmE0ZWU3YzA4MDA5M2I5MDY3Zjg1YiIsImVtYWlsIjoidnl1bmdsZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjIyODc5ODQ4LCJleHAiOjE2MjQwODk0NDh9.DnkxmqzfNretOr0d6_hvFXI8P0-KX38WzlUDR6tAFuY

####
GET http://localhost:5000/api/category/all

####
PUT http://localhost:5000/api/auth/editProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmE0ZWU3YzA4MDA5M2I5MDY3Zjg1YiIsImVtYWlsIjoidnl1bmdsZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI0ODY0NDM1LCJleHAiOjE2MjYwNzQwMzV9.8QfbTd5LzHEGpNLNocnSEvfBB_MNnk3N8njiqVnCs-8
Content-Type: application/json

{
    "address":"a",
    "phoneNumber":"0983782942",
    "fullName":"Lê Nguyễn Hùng Vỹ"
}


####
POST http://localhost:5000/api/cart/addBill
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmE0ZWU3YzA4MDA5M2I5MDY3Zjg1YiIsImVtYWlsIjoidnl1bmdsZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI0ODY0NDM1LCJleHAiOjE2MjYwNzQwMzV9.8QfbTd5LzHEGpNLNocnSEvfBB_MNnk3N8njiqVnCs-8
Content-Type: application/json


{
    "products":[
        {
            "product":"60cde5ea54ccdf20583cd13f",
            "quantity":2
        }
    ],
    "total":12000
}


#####
GET  http://localhost:5000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmE0ZWU3YzA4MDA5M2I5MDY3Zjg1YiIsImVtYWlsIjoidnl1bmdsZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI0ODY0NDM1LCJleHAiOjE2MjYwNzQwMzV9.8QfbTd5LzHEGpNLNocnSEvfBB_MNnk3N8njiqVnCs-8


####
GET http://localhost:5000/api/cart/bills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmE0ZWU3YzA4MDA5M2I5MDY3Zjg1YiIsImVtYWlsIjoidnl1bmdsZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI0ODY0NDM1LCJleHAiOjE2MjYwNzQwMzV9.8QfbTd5LzHEGpNLNocnSEvfBB_MNnk3N8njiqVnCs-8



####
PUT http://localhost:5000/api/product/review/60cde5ea54ccdf20583cd13f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmFmNDAxODliYTI5NDQyMDRlZDQ0ZSIsImVtYWlsIjoidnl1bmdsZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlcyIsImlhdCI6MTYyNTMxODM4NCwiZXhwIjoxNjI2NTI3OTg0fQ.byZzybOFAHQOqulTwktnzJFbL51vCZk0zW4Pq_WpUbI
Content-Type: application/json

{
    "star":5,
    "body":"Chất lượng sản phẩm rất cao"
}